# Generated by Django 5.1.2 on 2024-10-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
