# Generated by Django 5.1.2 on 2024-10-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_coursepoint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoursePoint',
            new_name='Point',
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
