# Generated by Django 5.1.2 on 2024-10-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_course_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='point',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
