# Generated by Django 5.1.2 on 2024-10-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_point_completed_alter_point_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='material_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='point',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
